### ISSUE TITLE
在计算器内如何查看当前安装的系统版本？

### ISSUE THREAD

**Issue by Goldppx** [ExistOS-Team/ExistOS-For-HP39GII#104]
有时候没能刷写成功，不知道是否真的更新成功了的时候提交反馈会比较麻烦
有的话还请告诉我一下，我会积极参与测试的
没有的话，佬考虑在哪里加一个？

**Comment by yuuki410** [comment]
曾经有一个Build Time
自Build 90起删去了

**Comment by yuuki410** [comment]
恭喜，自 Build 106 起又有 Build Time 了
