### ISSUE TITLE
KhiCAS doesn't work since `build 107`

### ISSUE THREAD

**Issue by yuuki410** [ExistOS-Team/ExistOS-For-HP39GII#110]
It is unknown why KhiCAS doesn't work since `build 107`.  
Before I found the solution to fix this problem, please using the `build 106` or earlier builds.

@parisseb,  could I ask what I have broken in *[this commit](https://github.com/ExistOS-Team/ExistOS-For-HP39GII/commit/5ae46e277ba0812a2d148050d0b8ad620ed907c6)* that would prevent KhiCAS from working as usual.

Commit refer: https://github.com/ExistOS-Team/ExistOS-For-HP39GII/commit/5ae46e277ba0812a2d148050d0b8ad620ed907c6

**Comment by parisseb** [comment]
Sorry, I don't see. Why did you change the Makefile target path for the compiled libraries?

**Comment by yuuki410** [comment]
> Why did you change the Makefile target path for the compiled libraries?

Because it is a part in the ExistOS-For-HP39II project directory.

----

After rebuild all targets, it works, strange.

**Comment by parisseb** [comment]
I see a difference in khicas_stub.cpp, where at line 366 
lv_obj_invalidate(lv_scr_act());
has been commented. If I uncomment it, compilation fails. But on my "old" version of ExistOS, it is uncommented and it compiles correctly.
That's should be understood and is perhaps the reason why the keyboard does not work correctly.

**Comment by yuuki410** [comment]
> That's should be understood and is perhaps the reason why the keyboard does not work correctly.

Because of some key-codes are undefined in `keyboard.h`, and `console.cc` doesn't process them.
