### ISSUE TITLE
浮点数计算错误 /Float number calculating error 

### ISSUE THREAD

**Issue by iuang1** [ExistOS-Team/ExistOS-For-HP39GII#115]
版本：从[build 69](https://github.com/ExistOS-Team/ExistOS-For-HP39GII/releases/tag/build-69)到[build 114](https://github.com/ExistOS-Team/ExistOS-For-HP39GII/releases/tag/build-114)

如图
![IMG_20221230_213638](https://user-images.githubusercontent.com/97876916/210076053-921485e8-676c-4223-b4be-e4a85b382912.jpg)
问题复现: https://wwq.lanzouo.com/izYRu0jqsd5c

**Comment by yuuki410** [comment]
已确认自 Build 69 起存在此 Bug

**Comment by iuang1** [comment]
已修正

**Comment by parisseb** [comment]
That's an endianness issue. Switching to the complete port of KhiCAS will automatically fix it.

**Comment by iuang1** [comment]
Thanks

**Comment by yuuki410** [comment]
Resolved in [v1.1.4](https://github.com/ExistOS-Team/ExistOS-For-HP39GII/releases/tag/v1.1.4)
