### ISSUE TITLE
萌新开发者想问一下正确的开发姿势

### ISSUE THREAD

**Issue by Oyami-Srk** [ExistOS-Team/ExistOS-For-HP39GII#40]
本菜鸡对这个项目十分感兴趣，目前正在研究代码，有几个小小的问题想问一下。

- 一般的开发-Debug流程是什么？应该不会是来回按ON/C+插拔USB线吧，这样感觉有点麻烦。
- 有通过JTAG调试程序的方法吗？

以及有没有QQ群之类的能够交流一下（

EDIT: 按照Datasheet把BOOT MODE设置成USB之后就不用按ON/C了，方便了一点。
话说都能格式化NAND了，为啥还说”没搞清固件刷入机制“，难道不是按照Datasheet上的Layout写入就行了吗？

**Comment by AliasQli** [comment]
欢迎新的开发者！

可以加入我们的QQ群：942419621。

- 一般的开发流程基本上如你所言（
- 暂时没有，正准备加（
- 另外，SMTP3770的模拟器也在写了。

关于格式化NAND的问题，gii采用的是hp私有的分区格式，这种格式没能破解，相当于不清楚刷入机制。只有SMTP3770有Datasheet，gii是没有的。

**Comment by Repeerc** [comment]
JTAG有，但没完全由，在STMP3770上用的是SJTAG，把六线的并行JTAG转成了一线的串行JTAG，需要而外的硬件FPGA实现转换，或者购买现有的，价格300~400，还未尝试过
