### ISSUE TITLE
怎么刷回官方系统

### ISSUE THREAD

**Issue by lcjcjcjcj** [ExistOS-Team/ExistOS-For-HP39GII#53]
RT，刷入existOS之后怎么刷回官方系统
我用官方的updater工具和firmware.sb文件重刷，刷到一半（显示分配表）停下来了，之后不论是刷existOS还是官方工具重刷都不行，计算器开不了机，什么都显示不了

**Comment by Edge2020** [comment]
官方工具应该是可以刷回来的，卡在分配表的时候建议稍等一下，比较慢的。

**Comment by Edge2020** [comment]
而且39gii一般是刷不死的（

**Comment by lcjcjcjcj** [comment]
已经刷了三次了，每次卡分配表就卡出去了，还是说我的官方工具有问题？

**Comment by Edge2020** [comment]
> 

唔。。。有试过用这个工具先刷回existOS吗。
https://github.com/ExistOS-Team/ExistOS_Updater_v2

**Comment by Edge2020** [comment]
> 

或者可以尝试重装一下官方工具？

**Comment by lcjcjcjcj** [comment]
谢谢
另外还想请问一下有没有windows7可以使用的刷入工具

**Comment by Edge2020** [comment]
> 谢谢 另外还想请问一下有没有windows7可以使用的刷入工具

win7的话可以下载https://github.com/ExistOS-Team/ExistOS-For-HP39GII/tree/master/tools/sbtools_win里的sb_loader.exe

和https://github.com/ExistOS-Team/ExistOS-For-HP39GII/tree/master/tools里的edb.exe,

还有https://github.com/ExistOS-Team/ExistOS-For-HP39GII/releases/tag/Latest中的固件包

然后将下载的固件中的OSLoader.sb 、 System.sys 和 edb.exe 、 sb_loader.exe 放在同一目录中，


然后执行 sb_loader.exe -f OSLoader.sb

计算器自动重启后不要断开连接，

再执行edb.exe -r -s -f OSLoader.sb 1408 b -f ExistOS.sys 1984

计算器应当再次自动重启，然后自动进入ExistOS。

**Comment by lcjcjcjcj** [comment]
谢谢

**Comment by Edge2020** [comment]
> 谢谢

现在刷回来了吗（

**Comment by lcjcjcjcj** [comment]
没有……

**Comment by lcjcjcjcj** [comment]
上文提到的几个工具，好像都下载不了
edge显示”无法访问此页面 检查 raw.githubusercontent.com 中是否存在拼写错误。”
进不去

**Comment by lcjcjcjcj** [comment]
也试过用win11重刷existOS，reconnect的时候就[host disconnected]卡出去了
现在就是两个系统都刷不了，计算器开不了机

**Comment by Edge2020** [comment]
> 上文提到的几个工具，好像都下载不了 edge显示”无法访问此页面 检查 raw.githubusercontent.com 中是否存在拼写错误。” 进不去

可能需要挂梯子（

传了百度网盘：

链接：https://pan.baidu.com/s/19thpRjbda7KeyS5Vxt0Ljg?pwd=bylp 

提取码：bylp

下载解压之后按住 `ON/C` 键将计算器连接至电脑，执行 `第一步.bat`

计算器自动重启后不要断开连接，

再执行 `第二步.bat`

计算器应当自动重启进入ExistOS。

**Comment by Edge2020** [comment]
> 
或者试试这个v1.0.3.1，我还没release

[ExistOS_Updater_v1.0.3.1.zip](https://github.com/ExistOS-Team/ExistOS-For-HP39GII/files/9391921/ExistOS_Updater_v1.0.3.1.zip)

**Comment by Edge2020** [comment]
> 也试过用win11重刷existOS，reconnect的时候就[host disconnected]卡出去了 现在就是两个系统都刷不了，计算器开不了机

固件请用 https://pan.baidu.com/s/19thpRjbda7KeyS5Vxt0Ljg?pwd=bylp 里的，

github-bot 自动编译的 OSLoader.sb 有问题，开不了机。

**Comment by lcjcjcjcj** [comment]
执行第二步会Waiting USB CDC Connect
计算器could not find the system
线也没松，重插也不行
//（起码比什么都不显示要令人安心）

**Comment by lcjcjcjcj** [comment]
谢谢，我刷回来了

**Comment by lcjcjcjcj** [comment]
如果换成官方的固件按照刚才的方法也可以刷吧？

**Comment by Edge2020** [comment]
> 

刷官方固件，

建议完全重装官方工具，

后续使用官方工具刷回官方固件。

Issue closed。

**Comment by Edge2020** [comment]
> 如果换成官方的固件按照刚才的方法也可以刷吧？

如果刷不回去的话随时可以开issue

**Comment by Edge2020** [comment]
> 如果换成官方的固件按照刚才的方法也可以刷吧？

还有建议在使用官方工具时勾选 `格式化数据区` ，说不定和这个有关系（

**Comment by lcjcjcjcj** [comment]
emmm…还是试了一下，使用官方工具的时候不论是否格式化都无法重新刷回原来的官方系统
卡在分配表，过一会自动退出，刷不回官方系统

**Comment by lcjcjcjcj** [comment]
这个时候计算器怎样都不会显示任何东西，但是可以刷回existOS

**Comment by Edge2020** [comment]
> emmm…还是试了一下，使用官方工具的时候不论是否格式化都无法重新刷回原来的官方系统 卡在分配表，过一会自动退出，刷不回官方系统

win7是实体机还是虚拟机？

**Comment by lcjcjcjcj** [comment]
实体机

**Comment by Edge2020** [comment]
> 

或许可以刷入ExistOS并开机，

然后按  `ON/C` + `F5` 选择擦除所有Flash，

之后再用官方工具试试？
