### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by OriAmphey** [ExistOS-Team/ExistOS-For-HP39GII#55]
#build22以及之前几个pre-release版本的osloader刷不进去（我只能凑合用旧的osloader），reboot那一步的时候屏幕不显示任何东西，机器变砖；；新系统的cpu频率显示很诡异，通常为33603516Mhz，全人类感谢我3360遍，而且我没搞明白怎么调节；khicas的字符显示不太正常，且屏幕显示有时会抽搐.

**Comment by Repeerc** [comment]
https://github.com/ExistOS-Team/ExistOS-For-HP39GII/releases/tag/Latest

用这个版本的osloader和system，因为系统更改了频率设置的接口，需要同时编译的osloader才能匹配，但是git自动编译生成的pre-release出来的osloader有问题所以没法运行刷入。
