### ISSUE TITLE
关于xcas的UI

### ISSUE THREAD

**Issue by smoothborewang** [ExistOS-Team/ExistOS-For-HP39GII#58]
1，建议字体大小可调整；
2，建议可自定义algb和calc的选项卡。

**Comment by yuuki410** [comment]
本项目使用的Khicas是XCas的CASIO Add-in移植版，若有问题请向其开发团队提出。

http://www-fourier.ujf-grenoble.fr/~parisse/giac.html

**Comment by yuuki410** [comment]
若需要自定义选项卡请编辑 `FMENU.cfg` 文件，在计算器 `/xcas` 目录下

调整字体大小请按 `Symb` 键
