### ISSUE TITLE
Unable to close warning window

### ISSUE THREAD

**Issue by LifeEmu** [ExistOS-Team/ExistOS-For-HP39GII#67]
Steps to reproduce:
1. Press [F3] to select `Status` tab
2. Select and check the checkbox `Enable Charge` and choose `OK` to enable charging
3. Switch to other tabs using [F1] or [F2]

Now the warning window will re-appear, and you will be unable to close it because you cannot focus on it.

(Also, pressing any key after step 2 makes the window re-appear, but in this case you will not lose control)

**Comment by yuuki410** [comment]
Fixed by replace LVGL with own UICore
