### ISSUE TITLE
My Calc is broken :(

### ISSUE THREAD

**Issue by Goldppx** [ExistOS-Team/ExistOS-For-HP39GII#76]
When I use ExistOSUpdater flash my calc,Something wrong happen and then my calc is broken.It can't connect to my PC(windows10).I try every ways on the HP helpguide but it still can't work
Could anyone Help Me???

**Comment by Edge2020** [comment]
Connect your calculator to computer with `ON/C` key pressed down. Then you can use [ExistOS Updater](https://github.com/ExistOS-Team/ExistOS_Updater_v2) to unbrick it.

**Comment by Goldppx** [comment]
> 
Without battery right？
I tried this way，my computer still doesn't recognize it.No any sign mean it connect right.

**Comment by Goldppx** [comment]
If [https://github.com/ExistOS-Team/ExistOS_Updater_v2](url) broke the base of the machine??

**Comment by Edge2020** [comment]
> 

Is there a new device appeared in Device Manager?
Or you can use another computer and try again.
STMP3770 has On-Chip Rom inside it, so it's not that possible to brick it.

**Comment by Goldppx** [comment]
> Is there a new device appeared in Device Manager? Or you can use another computer and try again. STMP3770 has On-Chip Rom inside it, so it's not that possible to brick it.

No ,i checked the device manager,there is no new device.I'll try to use another computer maybe somedays soon.
Thank u

**Comment by Goldppx** [comment]
Yeah,same cable,same PC.SUCCESS flash it!but I found another problem:
I use the ExistOS Update tool ,Choose lastest OSloader and system.Use hostlinkmode.
I can boot the system now but it run in the RAM.So I can't shutdown or do anything about power.
How to flash OSloader on this machine so that make it work?Only can do this by using Ninja?

**Comment by Edge2020** [comment]
> 
ExistOS Updater will flash OSLoader and System to flash after sending OSLoader to calculator RAM.

For example, I use HostLink mode to update my device, and after I pressed the `Update OSLoader&System` button, the application will send OSLoader to calculator RAM. Then, the calculator will reboot automatically, and the updater will flash OSLoader and System to calculator flash. Finally, the calculator will reboot the last time and enter the system. That's the whole progress of updating using HostLink Mode.

**Comment by Goldppx** [comment]
may I have your QQ or Wechat id？I want share a video.Things didn't happen like that you want
